version: '3.8'

services:

  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    links:
      - db
      - phpmyadmin
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - '8080:80'

  db:
    container_name: db
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci        
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: eYh1OrD6II
        MYSQL_DATABASE: id4ideas3
        MYSQL_USER: ideasUser
        MYSQL_PASSWORD: ideasPass
        TZ: 'America/Argentina/Buenos_Aires'
    ports:
        - '8081:3306'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_USER: ideasUser
      MYSQL_PASSWORD: ideasPass
      MYSQL_ROOT_PASSWORD: eYh1OrD6II 
      TZ: 'America/Argentina/Buenos_Aires'
    links:
      - db
